services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      APACHE_RUN_USER: $APACHE_RUN_USER
      APACHE_RUN_GROUP: $APACHE_RUN_GROUP

      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
    volumes:
      - ./site:/var/www/html # For autocompletion
      - ./dev/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./dev/wp-content/themes:/var/www/html/wp-content/themes

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

